# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ventivader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for Ventivader
  pod 'SwiftGifOrigin'
  pod 'Charts'
  
  target 'VentivaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
