# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ventivader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ventivader
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftGifOrigin'

  target 'VentivaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
